import type { TournamentSnapshot } from "@/entities/tournament/model/types";

// Builds a deterministic tournament snapshot for local UI work.
export function createDemoTournamentSnapshot(code: string): TournamentSnapshot {
  return {
    code: code.toUpperCase(),
    status: "IN_HAND",
    currentLevel: {
      level: 3,
      smallBlind: 25,
      bigBlind: 50,
      durationSeconds: 300,
    },
    nextLevel: {
      level: 4,
      smallBlind: 50,
      bigBlind: 100,
      durationSeconds: 300,
    },
    levelEndsAtEpochSecond: Math.floor(Date.now() / 1000) + 173,
    secondsUntilNextLevel: 173,
    mainPot: 460,
    sidePots: [
      {
        id: "side-1",
        type: "SIDE",
        amount: 150,
        eligibleGuestIds: ["guest-player", "guest-mina", "guest-noah"],
      },
    ],
    boardCards: ["AH", "KD", "7C", "4S"],
    dealerSeat: 1,
    smallBlindSeat: 2,
    bigBlindSeat: 3,
    actingSeat: 4,
    players: [
      {
        guestId: "guest-player",
        nickname: "Player One",
        seatIndex: 0,
        status: "FOLDED",
        stack: 825,
        owner: true,
        connected: true,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-mina",
        nickname: "Mina",
        seatIndex: 1,
        status: "ACTIVE",
        stack: 640,
        owner: false,
        connected: true,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-alex",
        nickname: "Alex",
        seatIndex: 2,
        status: "ALL_IN",
        stack: 0,
        owner: false,
        connected: true,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-jin",
        nickname: "Jin",
        seatIndex: 3,
        status: "ACTIVE",
        stack: 1190,
        owner: false,
        connected: true,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-noah",
        nickname: "Noah",
        seatIndex: 4,
        status: "ACTIVE",
        stack: 510,
        owner: false,
        connected: true,
        participating: true,
        acting: true,
      },
      {
        guestId: "guest-sora",
        nickname: "Sora",
        seatIndex: 5,
        status: "BUSTED_OUT",
        stack: 0,
        owner: false,
        connected: false,
        participating: false,
        acting: false,
      },
    ],
    showdownPots: [],
    availableActions: ["FOLD", "CALL", "RAISE", "ALL_IN"],
    tableMessage: "Noah is facing action for 50 more chips. Side pot is active.",
  };
}
