import type { TournamentSnapshot } from "@/entities/tournament/model/types";

// Builds a deterministic tournament snapshot for local UI work.
export function createDemoTournamentSnapshot(code: string, roomName = "금요 홀덤 싯앤고"): TournamentSnapshot {
  return {
    code: code.toUpperCase(),
    roomName,
    visibility: "PRIVATE",
    handNumber: 1,
    stateVersion: 1,
    snapshotAudience: "VIEWER",
    viewerGuestId: "guest-player",
    viewerHoleCardsIncluded: true,
    status: "IN_HAND",
    currentLevel: {
      level: 3,
      smallBlind: 25,
      bigBlind: 50,
      durationSeconds: 300,
    },
    nextLevel: {
      level: 4,
      smallBlind: 50,
      bigBlind: 100,
      durationSeconds: 300,
    },
    levelEndsAtEpochSecond: Math.floor(Date.now() / 1000) + 173,
    secondsUntilNextLevel: 173,
    mainPot: 460,
    sidePots: [
      {
        id: "side-1",
        type: "SIDE",
        amount: 150,
        eligibleGuestIds: ["guest-player", "guest-mina", "guest-noah"],
      },
    ],
    boardCards: ["AH", "KD", "7C", "4S"],
    dealerSeat: 1,
    smallBlindSeat: 2,
    bigBlindSeat: 3,
    actingSeat: 4,
    paused: false,
    pauseReason: null,
    actionDeadlineAtEpochMilli: Date.now() + 14_000,
    actionTimeoutSeconds: 20,
    players: [
      {
        guestId: "guest-player",
        nickname: "플레이어1",
        seatIndex: 0,
        status: "FOLDED",
        stack: 825,
        roundContribution: 0,
        owner: true,
        connected: true,
        afk: false,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-mina",
        nickname: "Mina",
        seatIndex: 1,
        status: "ACTIVE",
        stack: 640,
        roundContribution: 0,
        owner: false,
        connected: true,
        afk: false,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-alex",
        nickname: "Alex",
        seatIndex: 2,
        status: "ALL_IN",
        stack: 0,
        roundContribution: 25,
        owner: false,
        connected: true,
        afk: false,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-jin",
        nickname: "Jin",
        seatIndex: 3,
        status: "ACTIVE",
        stack: 1190,
        roundContribution: 50,
        owner: false,
        connected: true,
        afk: false,
        participating: true,
        acting: false,
      },
      {
        guestId: "guest-noah",
        nickname: "Noah",
        seatIndex: 4,
        status: "ACTIVE",
        stack: 510,
        roundContribution: 0,
        owner: false,
        connected: true,
        afk: false,
        participating: true,
        acting: true,
      },
      {
        guestId: "guest-sora",
        nickname: "Sora",
        seatIndex: 5,
        status: "BUSTED_OUT",
        stack: 0,
        roundContribution: 0,
        owner: false,
        connected: false,
        afk: false,
        participating: false,
        acting: false,
      },
    ],
    showdownPots: [],
    showdownHands: [],
    recentlyBustedGuestIds: [],
    availableActions: ["FOLD", "CALL", "RAISE", "ALL_IN"],
    chipsToCall: 50,
    minimumRaiseTo: 100,
    tableMessage: "Noah is up. Call 50 more to continue, and a side pot is active.",
    selfHandLabel: "Q 원페어",
    selfHoleCards: ["QS", "QH"],
  };
}
