spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.metrics.SystemMetricsAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.metrics.web.tomcat.TomcatMetricsAutoConfiguration
  jpa:
    show-sql: false

server:
  forward-headers-strategy: framework

logging:
  level:
    com.texasholdem: info
    org.springframework.web.socket: info
